INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO in _internal: [33mPress CTRL+C to quit[0m
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:17:26] "GET / HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:18:18] "[31m[1mGET /login HTTP/1.1[0m" 405 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:18:29] "POST /login HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:21:19] "[31m[1mGET /categories HTTP/1.1[0m" 405 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:26:38] "[31m[1mGET /categories HTTP/1.1[0m" 405 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:26:48] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:27:08] "POST /login HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:28:24] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:28:42] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:28:44] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
ERROR in app: Exception on /categories [GET]
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'
ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1844, in finalize_request
    response = self.process_response(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2337, in process_response
    response = self.ensure_sync(func)(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:30:31] "[35m[1mGET /categories HTTP/1.1[0m" 500 -
ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
ERROR in app: Exception on /categories [GET]
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'
ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1844, in finalize_request
    response = self.process_response(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2337, in process_response
    response = self.ensure_sync(func)(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:31:21] "[35m[1mGET /categories HTTP/1.1[0m" 500 -
ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
ERROR in app: Exception on /categories [GET]
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'
ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1844, in finalize_request
    response = self.process_response(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2337, in process_response
    response = self.ensure_sync(func)(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:31:22] "[35m[1mGET /categories HTTP/1.1[0m" 500 -
ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
ERROR in app: Exception on /categories [GET]
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'
ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1844, in finalize_request
    response = self.process_response(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2337, in process_response
    response = self.ensure_sync(func)(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:31:23] "[35m[1mGET /categories HTTP/1.1[0m" 500 -
ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
ERROR in app: Exception on /categories [GET]
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'
ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1844, in finalize_request
    response = self.process_response(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2337, in process_response
    response = self.ensure_sync(func)(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:31:25] "[35m[1mGET /categories HTTP/1.1[0m" 500 -
ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
TypeError: create_category() missing 1 required positional argument: 'current_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:32:04] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:32:25] "[31m[1mPOST /login HTTP/1.1[0m" 400 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:32:37] "POST /login HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:33:39] "[31m[1mGET /notes HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:36:07] "POST /login HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:37:26] "[31m[1mGET /notes HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:37:51] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:38:31] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:38:32] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:38:33] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:38:34] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:38:34] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:38:35] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:38:35] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:38:36] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:42:18] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:42:19] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:42:20] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:42:21] "[31m[1mGET /categories HTTP/1.1[0m" 401 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:42:32] "GET /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:42:45] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:43:32] "GET /notes HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:44:06] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:44:10] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:44:43] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:44:43] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:44:43] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:44:43] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:44:46] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
ERROR in app: Exception on /categories [GET]
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\helpers.py", line 209, in make_response
    return current_app.make_response(args)  # type: ignore
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'create_category' did not return a valid response. The function either returned None or ended without a return statement.
ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\helpers.py", line 209, in make_response
    return current_app.make_response(args)  # type: ignore
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'create_category' did not return a valid response. The function either returned None or ended without a return statement.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1844, in finalize_request
    response = self.process_response(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2337, in process_response
    response = self.ensure_sync(func)(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 18:45:33] "[35m[1mGET /categories HTTP/1.1[0m" 500 -
ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\helpers.py", line 209, in make_response
    return current_app.make_response(args)  # type: ignore
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'create_category' did not return a valid response. The function either returned None or ended without a return statement.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO in _internal: [33mPress CTRL+C to quit[0m
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:26:04] "POST /login HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:33:18] "POST /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:33:38] "POST /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:33:47] "POST /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:34:05] "POST /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:34:17] "POST /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:34:23] "POST /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:34:25] "POST /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:34:43] "[31m[1mGET /categories HTTP/1.1[0m" 400 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
ERROR in app: Exception on /categories [GET]
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\helpers.py", line 209, in make_response
    return current_app.make_response(args)  # type: ignore
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'create_category' did not return a valid response. The function either returned None or ended without a return statement.
ERROR in app: Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\helpers.py", line 209, in make_response
    return current_app.make_response(args)  # type: ignore
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'create_category' did not return a valid response. The function either returned None or ended without a return statement.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1844, in finalize_request
    response = self.process_response(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2337, in process_response
    response = self.ensure_sync(func)(response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:36:21] "[35m[1mGET /categories HTTP/1.1[0m" 500 -
ERROR in _internal: Error on request:
Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\helpers.py", line 209, in make_response
    return current_app.make_response(args)  # type: ignore
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'create_category' did not return a valid response. The function either returned None or ended without a return statement.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\extension.py", line 182, in cors_after_request
    if try_match(normalized_path, res_regex):
  File "C:\Users\alkha\Desktop\All Projects\Klerc\Klerc\venv\lib\site-packages\flask_cors\core.py", line 280, in try_match
    return re.match(maybe_regex, request_origin, flags=re.IGNORECASE)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\alkha\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:37:20] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:38:43] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:40:22] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:41:53] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:43:44] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:46:27] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:48:24] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:49:09] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:50:36] "GET /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:51:03] "POST /categories HTTP/1.1" 200 -
INFO in _internal: 127.0.0.1 - - [07/Jan/2023 23:51:09] "GET /categories HTTP/1.1" 200 -
INFO in _internal:  * Detected change in 'C:\\Users\\alkha\\Desktop\\All Projects\\Klerc\\Klerc\\src\\app.py', reloading
INFO in _internal:  * Restarting with stat
